export const USER_MESSAGE = {
  VALIDATION_ERROR: 'Validation is error',
  USER_NOT_FOUND: 'User not found!',
  USER_EXIST: 'User is already exits',
  EMAIL_INVALID: 'Email is invalid',
  EMAIL_REQUIRED: 'Email is required',
  PASSWORD_INVALID: 'Password is invalid',
  PASSWORD_MUST_BE_STRONG:
    'Password must be 6 characters and include at least 1 character, 1 uppercase and 1 lowercase character',
  CONFIRM_PASSWORD_NOT_MATCH: 'Confirm password is not matching with password',
  LOGIN_SUCCESS: 'Login successfully',
  LOGIN_FAIL: 'Login Fail',
  ACCESS_TOKEN_REQUIRED: 'Access token is required',
  REFRESH_TOKEN_REQUIRED: 'Refresh token is required',
  ACCESS_TOKEN_INVALID: 'Access token is invalid',
  REFRESH_TOKEN_USED_OR_INVALID: 'Refresh token has been used or is not valid',
  LOGOUT_SUCCESS: 'Logout successfully',
  EMAIL_VERIFY_TOKEN_REQUIRED: 'Email verify token is required',
  EMAIL_VERIFY_TOKEN_ALREADY_USED_BEFORE: 'Email verify token is already used before',
  EMAIL_VERIFY_TOKEN_SUCCESS: 'Email verify success',
  NEW_PASSWORD: 'New password is invalid',
  RESEND_EMAIL_VERIFY_TOKEN: 'Resend email verify token is successful',
  CHECK_EMAIL_TO_RESET_PASSWORD: 'Check email to reset password ',
  VERIFY_FORGOT_PASSWORD_TOKEN_ALREADY_USED_BEFORE: ' verify forgot password token is already used before'
}
